### ISSUE TITLE
worker is stopped in while loop on Windows OS

### ISSUE THREAD

**Issue by greentec** [lasseuth1/blood_bowl2#4]
The game stops playing. When I print information for debug, it seems that the worker has an endless loop in the while loop. Is it a multi-process issue only on Windows OS?

https://github.com/lasseuth1/blood_bowl2/blob/dbe54bfca929ae411e7e70f9359fbbc8c899dc8a/rarity_of_events/arguments.py#L22

I changed num_processes to 1 or 2, but the game stops soon.

**Comment by DKuan** [comment]
I meet the problem as you do. I deal with it by resuming the train after closing the wrong one.

**Comment by greentec** [comment]
@DKuan Did you check the last update of ffai(https://github.com/njustesen/ffai/commit/b0780ab68078fe8c9333394a2485e2905e75b478)? I downloaded and tested this, and in 5vs5 games to 22000 episodes I did not experience stopping.

**Comment by greentec** [comment]
At first I thought it was a multiprocessor problem for windows os, but when I deleted the multiprocessor part, I got a problem again and told @njustesen and he fixed some code.

**Comment by greentec** [comment]
I think this issue does not seem to be happening at the moment, and it seems to be solved by an external code modification, so I will close the issue.
